sudo: required
service:
  - docker

before_install:
  - docker build -t deathstroke143/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true deathstroke143/react-test npm run test

after_success:
  - docker build -t deathstroke143/multi-client ./client
  - docker build -t deathstroke143/multi-nginx ./nginx
  - docker build -t deathstroke143/multi-server ./server
  - docker build -t deathstroke143/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push them to docker hub
  - docker push deathstroke143/multi-client
  - docker push deathstroke143/multi-nginx
  - docker push deathstroke143/multi-server
  - docker push deathstroke143/multi-worker